### ISSUE TITLE
Suggestion: use `Accept` header to request different representations of data

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-server#2]
My understanding of the `/features` route is that it is a GeoJSON representation of the observation data. I think we should use the `Accept` header in the request, keeping the same endpoint (`/observations`). The [mime-type for GeoJSON](https://www.iana.org/assignments/media-types/application/geo+json) is `application/geo+json`. E.g.

```
curl -I -H 'Accept: application/geo+json' http://mapeo-server.com/observations
```

We should probably do the same for individual observation records (return as GeoJSON Feature instead of raw json record) just to keep things consistent.

But... Do we need to support GeoJSON on the API level or should this be left to the client? @karissa

**Comment by noffle** [comment]
I'm flexible -- since it's not a complex operation -- though I thought we agreed at the retreat that the backend would just serve up observation objects and the client would map that to GeoJSON as it goes.

**Comment by karissa** [comment]
Yeah that snuck in there, we don't need it. `Accept` headers are annoying to deal with although fine to `Accept` them (haha). If we want to support this feature we can add both that and `/observations.geojson`, which would be my preference.

**Comment by noffle** [comment]
Closing this for now: let's add support for other formats as we need them.
