### ISSUE TITLE
Handling media files

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-server#5]
So [react-native-camera](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md) returns a uri path to where the photo has been saved. It can return a base64 representation of the image, but that is expensive. Any transfer between the native and react-native thread takes time.

According to the react-native-camera docs the photos are saved to the "Application cache folder", i'm not sure where this is.

1. Do we want to leave them in this folder or cache them?
2. Should the node process or react-native be responsible for moving them?

My initial feeling is node should move them.

I don't think we will be using the media route to POST photos. I think that's always going to involve expensive communication back and forth across the react-native bridge. Similarly I don't think the server should serve (GET) the photos either. The observation data should encode the photo filesystem location. The actual rendering in react-native happens on the native thread, so if you render a photo with an <Image> and link to the filesystem everything is happening in native.

How do we store photos in observations? I think with a unique filename or relative path. One of the endpoints should return the info necessary to construct the filesystem path from the filename/relative path of the observation records.

Pending question: What access to the filesystem does the node process have? Can it access external media (SD card)? Can it move files around? Maybe @staltz knows.

@noffle @czengg @howdyitshelena

**Comment by karissa** [comment]
It'd be great if the react-native process handled resizing, moving, and rendering. That way the node process just only has to handle receiving the filepath and saving that information in the db.

**Comment by gmaclennan** [comment]
I'm pretty sure it will be. Plus, react-native cannot do blobs, everything needs to be in base64.

I think the p2p db / observation db should store either a unique id / filename and everything in a flat file structure, or a relative filepath like we were doing with the current media sync used with tizii-tizii with subfolders created from the filename. We should never be storing absolute filepaths anyway.

**Comment by noffle** [comment]
FYI We resolved this by having the RN process passes absolute filename to node process, which makes a local copy in its `fs-blob-store`
